language: objective-c
osx_image: xcode9.1

script:
  - xcodebuild -workspace HowOld.xcworkspace -scheme 'HowOld' -sdk iphonesimulator build
  - xcodebuild test -workspace HowOld.xcworkspace -scheme 'HowOldTests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.1'
  - xcodebuild test -workspace HowOld.xcworkspace -scheme 'HowOldUITests' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.1'